name: Ruby on Rails CI

on:
  pull_request:
    branches:
      - master
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and run Docker container
      run: |
        docker-compose -f docker-compose.yml up -d --build
        docker-compose -f docker-compose.yml exec app bundle exec rake db:create
        docker-compose -f docker-compose.yml exec app bundle exec rake db:schema:load
        docker-compose -f docker-compose.yml exec app bundle exec rspec

    - name: Shutdown Docker container
      run: docker-compose -f docker-compose.yml down
