name: Ruby on Rails CI

on:
  pull_request:
    branches:
      - master
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get user UID and GID
      id: get_uid_gid
      run: |
        echo "::set-output name=uid::$(id -u)"
        echo "::set-output name=gid::$(id -g)"

    - name: Build and run Docker container
      env:
        ARG_USER_UID: ${{ steps.get_uid_gid.outputs.uid }}
        ARG_USER_GID: ${{ steps.get_uid_gid.outputs.gid }}
      run: |
        docker-compose -f docker-compose.yml build --build-arg ARG_USER_UID=${ARG_USER_UID} --build-arg ARG_USER_GID=${ARG_USER_GID}
        docker-compose -f docker-compose.yml up -d
        docker-compose -f docker-compose.yml exec -T app bundle exec rake db:create
        docker-compose -f docker-compose.yml exec -T app bundle exec rake db:schema:load
        docker-compose -f docker-compose.yml exec -T app bundle exec rspec

    - name: Shutdown Docker container
      run: docker-compose -f docker-compose.yml down
