name: Ruby on Rails CI

on:
  pull_request:
    branches:
      - master
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2

    - name: Install Node.js and Yarn
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Set up PostgreSQL
      run: |
        sudo service postgresql start
        bundle exec rake db:create
        bundle exec rake db:schema:load

    - name: Run tests
      run: |
        bundle exec rspec
