name: Ruby on Rails CI

on:
  pull_request:
    branches:
      - master
      - homolog

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Build and test Rails app
        run: |
          docker build --build-arg ARG_RUBY_VERSION=3.0.2 -t my-rails-app .
          docker run \
            -e RAILS_ENV=test \
            -e DATABASE_HOST=postgres \
            -e DATABASE_PORT=5432 \
            -e DATABASE_USERNAME=user \
            -e DATABASE_PASSWORD=password \
            my-rails-app \
            bundle exec rake db:create db:schema:load
          docker run -e RAILS_ENV=test my-rails-app bundle exec rspec
